### ISSUE TITLE
How to apply the CSS style to the contents?

### ISSUE THREAD

**Issue by skmatz** [hiroppy/fusuma#162]
I use

```html
<div>
<!-- contents -->
</div>
```

to display TOC.  
Now, I did not understand how to apply the CSS style (for example, make the characters larger) to this.

Is that possible?

**Comment by hiroppy** [comment]
We can access a class directly.

ToC: https://hiroppy.github.io/fusuma/intro/#slide=2

```css
.toc {
  color: back;
}
```

**Comment by skmatz** [comment]
Thanks, but it looks like the style can not be applied to the title, even though the index and page number styles could be changed.

My css:

```css
.toc ol li {
  font-size: 100px;
}
```
