### ISSUE TITLE
Mermaid/flowchart support?

### ISSUE THREAD

**Issue by aemadrid** [hiroppy/fusuma#68]
what would it take to support Mermaid or Flowchart.js to have diagrams in my markdown?

**Comment by hiroppy** [comment]
You can inject javascript code.

```yml
# .fusumarc.yml

extends:
  js: index.js
```
