### ISSUE TITLE
How to add extra js dependency?

### ISSUE THREAD

**Issue by Roger-luo** [hiroppy/fusuma#79]
e.g I would like to use https://lab.lepture.com/github-cards/ to add card to it, how do I add this as dependency in `<head>`  with `<script>` is it possible? thanks!

**Comment by hiroppy** [comment]
Now, you can extend javascript.

e.g.

```yml
# fusumarc.yml
extends:
  js: index.js
```

```js
//  index.js
import 'your-library';
```

Or, do you want to customize HTML?
